### ISSUE TITLE
Please add support for "Message of the Day" (motd)

### ISSUE THREAD

**Issue by TheShihan** [skullernet/openffa#2]
Would it be possible for your to add support for a "message of the day file"? E.g. a "motd.txt" could be placed in the mod directory and the content of the file would be shown to new players joining the server for some seconds.

You could maybe borrow some of the code from lithium II? :-)

**Comment by Niehztog** [comment]
Hello @TheShihan,

its not necessary for the mod to implement "message of the day" support, since Q2Admin, which is almost standard on all servers, implements it. Just install Q2Admin on your server and see the readme.txt file [here](https://github.com/tastyspleen/q2admin-tsmod).

Q2Admin has some more nice features which gives additional options to the admin and the players, as for example map voting.
